name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        echo "SSH Host: ${{ secrets.SSH_HOST }}"
        echo "SSH Port: ${{ secrets.SSH_PORT }}"
        ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -o ConnectTimeout=10 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "SSH connection successful"'
        
    - name: Deploy to server
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/mutfakyapimnet/public_html/b2bb2c.mutfakyapim.net
          # Git pull
          git pull origin main
          
          # Composer dependencies güncelle
          composer install --no-interaction
          
          # .env dosyasını kopyala
          cp .env.production .env
          
          # .env dosyasını düzenle
          sed -i 's/^APP_URL=.*/APP_URL=https:\/\/b2bb2c.mutfakyapim.net/' .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=mutfakyapimnet_b2bb2c/' .env
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=mutfakyapimnet_b2bb2c/' .env
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=MUep6BUvBajj/' .env
          # Debug true kalacak, değiştirme
          # Key generate
          php artisan key:generate --force

          # Laravel cache temizle ve yeniden oluştur
          php artisan config:clear
          php artisan config:cache
          php artisan route:clear
          php artisan route:cache
          php artisan view:clear
          php artisan view:cache
          
          # Database migrations çalıştır (eğer varsa)
          php artisan migrate --force
          
          # Storage link oluştur (eğer yoksa)
          php artisan storage:link
          
          # Dosya izinlerini düzenle
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          
          # Storage ve cache dizinleri için özel izinler
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache
          
          # NPM dependencies (eğer frontend assets varsa)
          npm ci --production
          npm run build
          
          # Maintenance mode kapat
          $PHP_PATH artisan up
          
          echo "Deploy completed successfully!"
        EOF