name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        echo "SSH Host: ${{ secrets.SSH_HOST }}"
        echo "SSH Port: ${{ secrets.SSH_PORT }}"
        ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Test SSH connection
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -o ConnectTimeout=10 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "SSH connection successful"'
        
    - name: Deploy to server
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/mutfakyapimnet/public_html/b2bb2c.mutfakyapim.net
          
          # PHP yolunu belirle (cPanel için)
          export PHP_PATH=$(which php)
          echo "PHP Path: $PHP_PATH"
          
          # Maintenance mode aktif et
          $PHP_PATH artisan down
          
          # Git pull
          git pull origin main
          
          # Composer dependencies güncelle
          /usr/local/bin/composer install --no-dev --optimize-autoloader
          
          # Laravel cache temizle ve yeniden oluştur
          $PHP_PATH artisan config:clear
          $PHP_PATH artisan config:cache
          $PHP_PATH artisan route:clear
          $PHP_PATH artisan route:cache
          $PHP_PATH artisan view:clear
          $PHP_PATH artisan view:cache
          
          # Database migrations çalıştır (eğer varsa)
          $PHP_PATH artisan migrate --force
          
          # Storage link oluştur (eğer yoksa)
          $PHP_PATH artisan storage:link
          
          # Dosya izinlerini düzenle
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          
          # Storage ve cache dizinleri için özel izinler
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache
          
          # NPM dependencies (eğer frontend assets varsa)
          npm ci --production
          npm run build
          
          # Maintenance mode kapat
          $PHP_PATH artisan up
          
          echo "Deploy completed successfully!"
        EOF